paths:
    /products:
        get:
            description: Return a list of products from the database
            operationId: listProducts
            responses:
                "200":
                    $ref: '#/responses/productResponse'
            tags:
                - products
        post:
            description: Create a new product
            operationId: createProduct
            responses:
                "200":
                    $ref: '#/responses/productResponse'
                "422":
                    $ref: '#/responses/errorValidation'
                "501":
                    $ref: '#/responses/errorResponse'
            tags:
                - products
        put:
            description: Update a products details
            operationId: updateProduct
            responses:
                "201":
                    $ref: '#/responses/noContentResponse'
                "404":
                    $ref: '#/responses/errorResponse'
                "422":
                    $ref: '#/responses/errorValidation'
            tags:
                - products
    /products/{id}:
        delete:
            description: Update a products details
            operationId: deleteProduct
            responses:
                "201":
                    $ref: '#/responses/noContentResponse'
                "404":
                    $ref: '#/responses/errorResponse'
                "501":
                    $ref: '#/responses/errorResponse'
            tags:
                - products
        get:
            description: Return a list of products from the database
            operationId: listSingle
            responses:
                "200":
                    $ref: '#/responses/productResponse'
                "404":
                    $ref: '#/responses/errorResponse'
            tags:
                - products
responses:
    errorResponse:
        description: ""
    errorValidation:
        description: ""
    noContentResponse:
        description: ""
    productResponse:
        description: Product defines the structure for an API product
        headers:
            description:
                description: |-
                    the description for this poduct

                    required: false
                maxLength: 10000
                type: string
            id:
                description: |-
                    the id for the product

                    required: false
                format: int64
                minimum: 1
                type: integer
            name:
                description: |-
                    the name for this poduct

                    required: true
                maxLength: 255
                type: string
            price:
                description: |-
                    the price for the product

                    required: true
                format: float
                minimum: 0.01
                type: number
            sku:
                description: |-
                    the SKU for the product

                    required: true
                pattern: '[a-z]+-[a-z]+-[a-z]+'
                type: string
swagger: "2.0"
